=== YashJanjarukiya1/XML-/XML/3.dtd
<!ELEMENT books (book)>
<!ELEMENT book (btitle+,subtitle,author+,pubyear)>
<!ELEMENT btitle (#PCDATA)>
<!ELEMENT subtitle EMPTY>
<!ELEMENT author (#PCDATA)>
<!ELEMENT pubyear (#PCDATA|REPRINT)*>
<!ELEMENT REPRINT (#PCDATA)>

=== YashJanjarukiya1/XML-/XML/3.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE books SYSTEM "3.dtd">
	<books>
		<book>
			<btitle>xml</btitle>
			<btitle>dbms</btitle>
			<subtitle></subtitle>
			<author>yash</author>
			<author>atul kahate</author>
			<pubyear>
				<REPRINT>2020</REPRINT>
			</pubyear>
		</book>
	</books>
